version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-server
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    working_dir: /app
    command: ["npm", "start"]
